name: Dialyzer

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: [21.3, 22.2]
        elixir: [1.9.4, 1.10.0]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install → Compile dependencies
        run: MIX_ENV=ci mix do deps.get, compile
      - name: Quality check
        run: |
          MIX_ENV=ci epmd -daemon
          MIX_ENV=ci mix quality.ci
